---
title: Serge Lavalette
timezone: UTC
collections:
  counters:
    title: Counters
    output: true
  events:
    title: Events
    output: true
  musics:
    title: Musics
    output: true
  posts:
    title: Posts
    output: true
  stores:
    title: Stores
    output: true
  uploads:
    title: Uploads
    output: true
  musicians:
    title: Musicians
    output: true
url: www.serge-lavalette.fr
baseurl:
email: contact@serge-lavalette.fr
future: true
markdown: kramdown
permalink: pretty
