---
title: Serge Lavalette
timezone: UTC
collections:
  counters:
    title: Counters
    output: true
  events:
    title: Events
    output: true
  musics:
    title: Musics
    output: true
  posts:
    title: Posts
    output: true
  stores:
    title: Stores
    output: true
  uploads:
    title: Uploads
    output: true
  musicians:
    title: Musicians
    output: true
url: www.serge-lavalette.fr
baseurl:
email: contact@serge-lavalette.fr
description: Serge Lavalette est un guitariste, chanteur, compositeur et interprête
  jazz. Après 30ans de concerts dans le monde, il lance son premier album « Back
  in Town ».
video:
  title: New record session
  id: igWSSYr154k
  height: 360
  width: 640
future: true
markdown: kramdown
permalink: pretty
