---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: _includes
  label: Sections
  create: all
  match: "**/*"
- type: directory
  path: _musicians
  label: Musiciens
  create: all
  match: "**/*"
- type: directory
  path: _stores
  label: Boutiques en ligne
  create: all
  match: "**/*"
- type: directory
  path: _musics
  label: Musiques
  create: all
  match: "**/*"
- type: directory
  path: _events
  label: Concerts
  create: all
  match: "**/*"
  templates:
  - concert
upload_dir: img
public_path: "/img"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
